#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWAPI_Data.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Awapi")]
	public partial class ConfigurationContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertawConfiguration(awConfiguration instance);
    partial void UpdateawConfiguration(awConfiguration instance);
    partial void DeleteawConfiguration(awConfiguration instance);
    #endregion
		
		public ConfigurationContextDataContext() : 
				base(global::AWAPI_Data.Properties.Settings.Default.AWAPIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConfigurationContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfigurationContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfigurationContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfigurationContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<awConfiguration> awConfigurations
		{
			get
			{
				return this.GetTable<awConfiguration>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awConfiguration")]
	public partial class awConfiguration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _configurationId;
		
		private string _alias;
		
		private string _title;
		
		private string _description;
		
		private string _fileServiceUrl;
		
		private string _contentServiceUrl;
		
		private string _blogServiceUrl;
		
		private string _pollServiceUrl;
		
		private string _automatedTaskServiceUrl;
		
		private string _twitterServiceUrl;
		
		private string _weatherServiceUrl;
		
		private string _adminBaseUrl;
		
		private string _fileDirectory;
		
		private string _fileMimeXMLPath;
		
		private bool _fileSaveOnAmazonS3;
		
		private string _fileAmazonS3BucketName;
		
		private string _fileAmazonS3AccessKey;
		
		private string _fileAmazonS3SecreyKey;
		
		private string _smtpServer;
		
		private System.DateTime _createDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnconfigurationIdChanging(long value);
    partial void OnconfigurationIdChanged();
    partial void OnaliasChanging(string value);
    partial void OnaliasChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnfileServiceUrlChanging(string value);
    partial void OnfileServiceUrlChanged();
    partial void OncontentServiceUrlChanging(string value);
    partial void OncontentServiceUrlChanged();
    partial void OnblogServiceUrlChanging(string value);
    partial void OnblogServiceUrlChanged();
    partial void OnpollServiceUrlChanging(string value);
    partial void OnpollServiceUrlChanged();
    partial void OnautomatedTaskServiceUrlChanging(string value);
    partial void OnautomatedTaskServiceUrlChanged();
    partial void OntwitterServiceUrlChanging(string value);
    partial void OntwitterServiceUrlChanged();
    partial void OnweatherServiceUrlChanging(string value);
    partial void OnweatherServiceUrlChanged();
    partial void OnadminBaseUrlChanging(string value);
    partial void OnadminBaseUrlChanged();
    partial void OnfileDirectoryChanging(string value);
    partial void OnfileDirectoryChanged();
    partial void OnfileMimeXMLPathChanging(string value);
    partial void OnfileMimeXMLPathChanged();
    partial void OnfileSaveOnAmazonS3Changing(bool value);
    partial void OnfileSaveOnAmazonS3Changed();
    partial void OnfileAmazonS3BucketNameChanging(string value);
    partial void OnfileAmazonS3BucketNameChanged();
    partial void OnfileAmazonS3AccessKeyChanging(string value);
    partial void OnfileAmazonS3AccessKeyChanged();
    partial void OnfileAmazonS3SecreyKeyChanging(string value);
    partial void OnfileAmazonS3SecreyKeyChanged();
    partial void OnsmtpServerChanging(string value);
    partial void OnsmtpServerChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    #endregion
		
		public awConfiguration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_configurationId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long configurationId
		{
			get
			{
				return this._configurationId;
			}
			set
			{
				if ((this._configurationId != value))
				{
					this.OnconfigurationIdChanging(value);
					this.SendPropertyChanging();
					this._configurationId = value;
					this.SendPropertyChanged("configurationId");
					this.OnconfigurationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alias", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				if ((this._alias != value))
				{
					this.OnaliasChanging(value);
					this.SendPropertyChanging();
					this._alias = value;
					this.SendPropertyChanged("alias");
					this.OnaliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(512)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileServiceUrl", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string fileServiceUrl
		{
			get
			{
				return this._fileServiceUrl;
			}
			set
			{
				if ((this._fileServiceUrl != value))
				{
					this.OnfileServiceUrlChanging(value);
					this.SendPropertyChanging();
					this._fileServiceUrl = value;
					this.SendPropertyChanged("fileServiceUrl");
					this.OnfileServiceUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contentServiceUrl", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string contentServiceUrl
		{
			get
			{
				return this._contentServiceUrl;
			}
			set
			{
				if ((this._contentServiceUrl != value))
				{
					this.OncontentServiceUrlChanging(value);
					this.SendPropertyChanging();
					this._contentServiceUrl = value;
					this.SendPropertyChanged("contentServiceUrl");
					this.OncontentServiceUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blogServiceUrl", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string blogServiceUrl
		{
			get
			{
				return this._blogServiceUrl;
			}
			set
			{
				if ((this._blogServiceUrl != value))
				{
					this.OnblogServiceUrlChanging(value);
					this.SendPropertyChanging();
					this._blogServiceUrl = value;
					this.SendPropertyChanged("blogServiceUrl");
					this.OnblogServiceUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pollServiceUrl", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string pollServiceUrl
		{
			get
			{
				return this._pollServiceUrl;
			}
			set
			{
				if ((this._pollServiceUrl != value))
				{
					this.OnpollServiceUrlChanging(value);
					this.SendPropertyChanging();
					this._pollServiceUrl = value;
					this.SendPropertyChanged("pollServiceUrl");
					this.OnpollServiceUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_automatedTaskServiceUrl", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string automatedTaskServiceUrl
		{
			get
			{
				return this._automatedTaskServiceUrl;
			}
			set
			{
				if ((this._automatedTaskServiceUrl != value))
				{
					this.OnautomatedTaskServiceUrlChanging(value);
					this.SendPropertyChanging();
					this._automatedTaskServiceUrl = value;
					this.SendPropertyChanged("automatedTaskServiceUrl");
					this.OnautomatedTaskServiceUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_twitterServiceUrl", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string twitterServiceUrl
		{
			get
			{
				return this._twitterServiceUrl;
			}
			set
			{
				if ((this._twitterServiceUrl != value))
				{
					this.OntwitterServiceUrlChanging(value);
					this.SendPropertyChanging();
					this._twitterServiceUrl = value;
					this.SendPropertyChanged("twitterServiceUrl");
					this.OntwitterServiceUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weatherServiceUrl", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string weatherServiceUrl
		{
			get
			{
				return this._weatherServiceUrl;
			}
			set
			{
				if ((this._weatherServiceUrl != value))
				{
					this.OnweatherServiceUrlChanging(value);
					this.SendPropertyChanging();
					this._weatherServiceUrl = value;
					this.SendPropertyChanged("weatherServiceUrl");
					this.OnweatherServiceUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminBaseUrl", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string adminBaseUrl
		{
			get
			{
				return this._adminBaseUrl;
			}
			set
			{
				if ((this._adminBaseUrl != value))
				{
					this.OnadminBaseUrlChanging(value);
					this.SendPropertyChanging();
					this._adminBaseUrl = value;
					this.SendPropertyChanged("adminBaseUrl");
					this.OnadminBaseUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileDirectory", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string fileDirectory
		{
			get
			{
				return this._fileDirectory;
			}
			set
			{
				if ((this._fileDirectory != value))
				{
					this.OnfileDirectoryChanging(value);
					this.SendPropertyChanging();
					this._fileDirectory = value;
					this.SendPropertyChanged("fileDirectory");
					this.OnfileDirectoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileMimeXMLPath", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string fileMimeXMLPath
		{
			get
			{
				return this._fileMimeXMLPath;
			}
			set
			{
				if ((this._fileMimeXMLPath != value))
				{
					this.OnfileMimeXMLPathChanging(value);
					this.SendPropertyChanging();
					this._fileMimeXMLPath = value;
					this.SendPropertyChanged("fileMimeXMLPath");
					this.OnfileMimeXMLPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileSaveOnAmazonS3", DbType="Bit NOT NULL")]
		public bool fileSaveOnAmazonS3
		{
			get
			{
				return this._fileSaveOnAmazonS3;
			}
			set
			{
				if ((this._fileSaveOnAmazonS3 != value))
				{
					this.OnfileSaveOnAmazonS3Changing(value);
					this.SendPropertyChanging();
					this._fileSaveOnAmazonS3 = value;
					this.SendPropertyChanged("fileSaveOnAmazonS3");
					this.OnfileSaveOnAmazonS3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileAmazonS3BucketName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fileAmazonS3BucketName
		{
			get
			{
				return this._fileAmazonS3BucketName;
			}
			set
			{
				if ((this._fileAmazonS3BucketName != value))
				{
					this.OnfileAmazonS3BucketNameChanging(value);
					this.SendPropertyChanging();
					this._fileAmazonS3BucketName = value;
					this.SendPropertyChanged("fileAmazonS3BucketName");
					this.OnfileAmazonS3BucketNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileAmazonS3AccessKey", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fileAmazonS3AccessKey
		{
			get
			{
				return this._fileAmazonS3AccessKey;
			}
			set
			{
				if ((this._fileAmazonS3AccessKey != value))
				{
					this.OnfileAmazonS3AccessKeyChanging(value);
					this.SendPropertyChanging();
					this._fileAmazonS3AccessKey = value;
					this.SendPropertyChanged("fileAmazonS3AccessKey");
					this.OnfileAmazonS3AccessKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileAmazonS3SecreyKey", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string fileAmazonS3SecreyKey
		{
			get
			{
				return this._fileAmazonS3SecreyKey;
			}
			set
			{
				if ((this._fileAmazonS3SecreyKey != value))
				{
					this.OnfileAmazonS3SecreyKeyChanging(value);
					this.SendPropertyChanging();
					this._fileAmazonS3SecreyKey = value;
					this.SendPropertyChanged("fileAmazonS3SecreyKey");
					this.OnfileAmazonS3SecreyKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smtpServer", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string smtpServer
		{
			get
			{
				return this._smtpServer;
			}
			set
			{
				if ((this._smtpServer != value))
				{
					this.OnsmtpServerChanging(value);
					this.SendPropertyChanging();
					this._smtpServer = value;
					this.SendPropertyChanged("smtpServer");
					this.OnsmtpServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
