#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWAPI_Data.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Awapi")]
	public partial class EmailTemplateContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertawSite_EmailTemplate(awSite_EmailTemplate instance);
    partial void UpdateawSite_EmailTemplate(awSite_EmailTemplate instance);
    partial void DeleteawSite_EmailTemplate(awSite_EmailTemplate instance);
    partial void InsertawEmailTemplate(awEmailTemplate instance);
    partial void UpdateawEmailTemplate(awEmailTemplate instance);
    partial void DeleteawEmailTemplate(awEmailTemplate instance);
    partial void InsertawBlog_EmailTemplate(awBlog_EmailTemplate instance);
    partial void UpdateawBlog_EmailTemplate(awBlog_EmailTemplate instance);
    partial void DeleteawBlog_EmailTemplate(awBlog_EmailTemplate instance);
    #endregion
		
		public EmailTemplateContextDataContext() : 
				base(global::AWAPI_Data.Properties.Settings.Default.AWAPIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EmailTemplateContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmailTemplateContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmailTemplateContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmailTemplateContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<awSite_EmailTemplate> awSite_EmailTemplates
		{
			get
			{
				return this.GetTable<awSite_EmailTemplate>();
			}
		}
		
		public System.Data.Linq.Table<awEmailTemplate> awEmailTemplates
		{
			get
			{
				return this.GetTable<awEmailTemplate>();
			}
		}
		
		public System.Data.Linq.Table<awBlog_EmailTemplate> awBlog_EmailTemplates
		{
			get
			{
				return this.GetTable<awBlog_EmailTemplate>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awSite")]
	public partial class awSite_EmailTemplate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _siteId;
		
		private string _alias;
		
		private string _title;
		
		private string _description;
		
		private bool _isEnabled;
		
		private string _cultureCode;
		
		private string _link;
		
		private string _imageurl;
		
		private System.Nullable<System.DateTime> _pubDate;
		
		private int _maxBlogs;
		
		private int _maxUsers;
		
		private int _maxContents;
		
		private string _accessKey;
		
		private string _grantedDomains;
		
		private string _bannedDomains;
		
		private string _twitterUsername;
		
		private string _twitterPassword;
		
		private System.Nullable<long> _userId;
		
		private System.Nullable<System.DateTime> _lastBuildDate;
		
		private System.Nullable<System.DateTime> _createDate;
		
		private EntitySet<awEmailTemplate> _awEmailTemplates;
		
		private EntitySet<awBlog_EmailTemplate> _awBlog_EmailTemplates;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsiteIdChanging(long value);
    partial void OnsiteIdChanged();
    partial void OnaliasChanging(string value);
    partial void OnaliasChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnisEnabledChanging(bool value);
    partial void OnisEnabledChanged();
    partial void OncultureCodeChanging(string value);
    partial void OncultureCodeChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnimageurlChanging(string value);
    partial void OnimageurlChanged();
    partial void OnpubDateChanging(System.Nullable<System.DateTime> value);
    partial void OnpubDateChanged();
    partial void OnmaxBlogsChanging(int value);
    partial void OnmaxBlogsChanged();
    partial void OnmaxUsersChanging(int value);
    partial void OnmaxUsersChanged();
    partial void OnmaxContentsChanging(int value);
    partial void OnmaxContentsChanged();
    partial void OnaccessKeyChanging(string value);
    partial void OnaccessKeyChanged();
    partial void OngrantedDomainsChanging(string value);
    partial void OngrantedDomainsChanged();
    partial void OnbannedDomainsChanging(string value);
    partial void OnbannedDomainsChanged();
    partial void OntwitterUsernameChanging(string value);
    partial void OntwitterUsernameChanged();
    partial void OntwitterPasswordChanging(string value);
    partial void OntwitterPasswordChanged();
    partial void OnuserIdChanging(System.Nullable<long> value);
    partial void OnuserIdChanged();
    partial void OnlastBuildDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastBuildDateChanged();
    partial void OncreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreateDateChanged();
    #endregion
		
		public awSite_EmailTemplate()
		{
			this._awEmailTemplates = new EntitySet<awEmailTemplate>(new Action<awEmailTemplate>(this.attach_awEmailTemplates), new Action<awEmailTemplate>(this.detach_awEmailTemplates));
			this._awBlog_EmailTemplates = new EntitySet<awBlog_EmailTemplate>(new Action<awBlog_EmailTemplate>(this.attach_awBlog_EmailTemplates), new Action<awBlog_EmailTemplate>(this.detach_awBlog_EmailTemplates));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alias", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				if ((this._alias != value))
				{
					this.OnaliasChanging(value);
					this.SendPropertyChanging();
					this._alias = value;
					this.SendPropertyChanged("alias");
					this.OnaliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(512)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isEnabled", DbType="Bit NOT NULL")]
		public bool isEnabled
		{
			get
			{
				return this._isEnabled;
			}
			set
			{
				if ((this._isEnabled != value))
				{
					this.OnisEnabledChanging(value);
					this.SendPropertyChanging();
					this._isEnabled = value;
					this.SendPropertyChanged("isEnabled");
					this.OnisEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cultureCode", DbType="VarChar(50)")]
		public string cultureCode
		{
			get
			{
				return this._cultureCode;
			}
			set
			{
				if ((this._cultureCode != value))
				{
					this.OncultureCodeChanging(value);
					this.SendPropertyChanging();
					this._cultureCode = value;
					this.SendPropertyChanged("cultureCode");
					this.OncultureCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(255)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageurl", DbType="VarChar(255)")]
		public string imageurl
		{
			get
			{
				return this._imageurl;
			}
			set
			{
				if ((this._imageurl != value))
				{
					this.OnimageurlChanging(value);
					this.SendPropertyChanging();
					this._imageurl = value;
					this.SendPropertyChanged("imageurl");
					this.OnimageurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pubDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> pubDate
		{
			get
			{
				return this._pubDate;
			}
			set
			{
				if ((this._pubDate != value))
				{
					this.OnpubDateChanging(value);
					this.SendPropertyChanging();
					this._pubDate = value;
					this.SendPropertyChanged("pubDate");
					this.OnpubDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxBlogs", DbType="Int NOT NULL")]
		public int maxBlogs
		{
			get
			{
				return this._maxBlogs;
			}
			set
			{
				if ((this._maxBlogs != value))
				{
					this.OnmaxBlogsChanging(value);
					this.SendPropertyChanging();
					this._maxBlogs = value;
					this.SendPropertyChanged("maxBlogs");
					this.OnmaxBlogsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxUsers", DbType="Int NOT NULL")]
		public int maxUsers
		{
			get
			{
				return this._maxUsers;
			}
			set
			{
				if ((this._maxUsers != value))
				{
					this.OnmaxUsersChanging(value);
					this.SendPropertyChanging();
					this._maxUsers = value;
					this.SendPropertyChanged("maxUsers");
					this.OnmaxUsersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxContents", DbType="Int NOT NULL")]
		public int maxContents
		{
			get
			{
				return this._maxContents;
			}
			set
			{
				if ((this._maxContents != value))
				{
					this.OnmaxContentsChanging(value);
					this.SendPropertyChanging();
					this._maxContents = value;
					this.SendPropertyChanged("maxContents");
					this.OnmaxContentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accessKey", DbType="VarChar(50)")]
		public string accessKey
		{
			get
			{
				return this._accessKey;
			}
			set
			{
				if ((this._accessKey != value))
				{
					this.OnaccessKeyChanging(value);
					this.SendPropertyChanging();
					this._accessKey = value;
					this.SendPropertyChanged("accessKey");
					this.OnaccessKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grantedDomains", DbType="VarChar(512)")]
		public string grantedDomains
		{
			get
			{
				return this._grantedDomains;
			}
			set
			{
				if ((this._grantedDomains != value))
				{
					this.OngrantedDomainsChanging(value);
					this.SendPropertyChanging();
					this._grantedDomains = value;
					this.SendPropertyChanged("grantedDomains");
					this.OngrantedDomainsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bannedDomains", DbType="VarChar(512)")]
		public string bannedDomains
		{
			get
			{
				return this._bannedDomains;
			}
			set
			{
				if ((this._bannedDomains != value))
				{
					this.OnbannedDomainsChanging(value);
					this.SendPropertyChanging();
					this._bannedDomains = value;
					this.SendPropertyChanged("bannedDomains");
					this.OnbannedDomainsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_twitterUsername", DbType="VarChar(50)")]
		public string twitterUsername
		{
			get
			{
				return this._twitterUsername;
			}
			set
			{
				if ((this._twitterUsername != value))
				{
					this.OntwitterUsernameChanging(value);
					this.SendPropertyChanging();
					this._twitterUsername = value;
					this.SendPropertyChanged("twitterUsername");
					this.OntwitterUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_twitterPassword", DbType="VarChar(50)")]
		public string twitterPassword
		{
			get
			{
				return this._twitterPassword;
			}
			set
			{
				if ((this._twitterPassword != value))
				{
					this.OntwitterPasswordChanging(value);
					this.SendPropertyChanging();
					this._twitterPassword = value;
					this.SendPropertyChanged("twitterPassword");
					this.OntwitterPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="BigInt")]
		public System.Nullable<long> userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastBuildDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastBuildDate
		{
			get
			{
				return this._lastBuildDate;
			}
			set
			{
				if ((this._lastBuildDate != value))
				{
					this.OnlastBuildDateChanging(value);
					this.SendPropertyChanging();
					this._lastBuildDate = value;
					this.SendPropertyChanged("lastBuildDate");
					this.OnlastBuildDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awSite_EmailTemplate_awEmailTemplate", Storage="_awEmailTemplates", ThisKey="siteId", OtherKey="siteId")]
		public EntitySet<awEmailTemplate> awEmailTemplates
		{
			get
			{
				return this._awEmailTemplates;
			}
			set
			{
				this._awEmailTemplates.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awSite_EmailTemplate_awBlog_EmailTemplate", Storage="_awBlog_EmailTemplates", ThisKey="siteId", OtherKey="siteId")]
		public EntitySet<awBlog_EmailTemplate> awBlog_EmailTemplates
		{
			get
			{
				return this._awBlog_EmailTemplates;
			}
			set
			{
				this._awBlog_EmailTemplates.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_awEmailTemplates(awEmailTemplate entity)
		{
			this.SendPropertyChanging();
			entity.awSite_EmailTemplate = this;
		}
		
		private void detach_awEmailTemplates(awEmailTemplate entity)
		{
			this.SendPropertyChanging();
			entity.awSite_EmailTemplate = null;
		}
		
		private void attach_awBlog_EmailTemplates(awBlog_EmailTemplate entity)
		{
			this.SendPropertyChanging();
			entity.awSite_EmailTemplate = this;
		}
		
		private void detach_awBlog_EmailTemplates(awBlog_EmailTemplate entity)
		{
			this.SendPropertyChanging();
			entity.awSite_EmailTemplate = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awEmailTemplate")]
	public partial class awEmailTemplate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _emailTemplateId;
		
		private long _siteId;
		
		private string _title;
		
		private string _description;
		
		private string _emailFrom;
		
		private string _emailSubject;
		
		private string _emailBody;
		
		private System.Nullable<long> _userId;
		
		private System.DateTime _lastBuildDate;
		
		private System.DateTime _createDate;
		
		private EntitySet<awBlog_EmailTemplate> _awBlog_EmailTemplates;
		
		private EntityRef<awSite_EmailTemplate> _awSite_EmailTemplate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnemailTemplateIdChanging(long value);
    partial void OnemailTemplateIdChanged();
    partial void OnsiteIdChanging(long value);
    partial void OnsiteIdChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnemailFromChanging(string value);
    partial void OnemailFromChanged();
    partial void OnemailSubjectChanging(string value);
    partial void OnemailSubjectChanged();
    partial void OnemailBodyChanging(string value);
    partial void OnemailBodyChanged();
    partial void OnuserIdChanging(System.Nullable<long> value);
    partial void OnuserIdChanged();
    partial void OnlastBuildDateChanging(System.DateTime value);
    partial void OnlastBuildDateChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    #endregion
		
		public awEmailTemplate()
		{
			this._awBlog_EmailTemplates = new EntitySet<awBlog_EmailTemplate>(new Action<awBlog_EmailTemplate>(this.attach_awBlog_EmailTemplates), new Action<awBlog_EmailTemplate>(this.detach_awBlog_EmailTemplates));
			this._awSite_EmailTemplate = default(EntityRef<awSite_EmailTemplate>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailTemplateId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long emailTemplateId
		{
			get
			{
				return this._emailTemplateId;
			}
			set
			{
				if ((this._emailTemplateId != value))
				{
					this.OnemailTemplateIdChanging(value);
					this.SendPropertyChanging();
					this._emailTemplateId = value;
					this.SendPropertyChanged("emailTemplateId");
					this.OnemailTemplateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="BigInt NOT NULL")]
		public long siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					if (this._awSite_EmailTemplate.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(512)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailFrom", DbType="NVarChar(100)")]
		public string emailFrom
		{
			get
			{
				return this._emailFrom;
			}
			set
			{
				if ((this._emailFrom != value))
				{
					this.OnemailFromChanging(value);
					this.SendPropertyChanging();
					this._emailFrom = value;
					this.SendPropertyChanged("emailFrom");
					this.OnemailFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailSubject", DbType="NVarChar(512)")]
		public string emailSubject
		{
			get
			{
				return this._emailSubject;
			}
			set
			{
				if ((this._emailSubject != value))
				{
					this.OnemailSubjectChanging(value);
					this.SendPropertyChanging();
					this._emailSubject = value;
					this.SendPropertyChanged("emailSubject");
					this.OnemailSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailBody", DbType="NVarChar(MAX)")]
		public string emailBody
		{
			get
			{
				return this._emailBody;
			}
			set
			{
				if ((this._emailBody != value))
				{
					this.OnemailBodyChanging(value);
					this.SendPropertyChanging();
					this._emailBody = value;
					this.SendPropertyChanged("emailBody");
					this.OnemailBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="BigInt")]
		public System.Nullable<long> userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastBuildDate", DbType="DateTime NOT NULL")]
		public System.DateTime lastBuildDate
		{
			get
			{
				return this._lastBuildDate;
			}
			set
			{
				if ((this._lastBuildDate != value))
				{
					this.OnlastBuildDateChanging(value);
					this.SendPropertyChanging();
					this._lastBuildDate = value;
					this.SendPropertyChanged("lastBuildDate");
					this.OnlastBuildDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awEmailTemplate_awBlog_EmailTemplate", Storage="_awBlog_EmailTemplates", ThisKey="emailTemplateId", OtherKey="commentEmailTemplateId")]
		public EntitySet<awBlog_EmailTemplate> awBlog_EmailTemplates
		{
			get
			{
				return this._awBlog_EmailTemplates;
			}
			set
			{
				this._awBlog_EmailTemplates.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awSite_EmailTemplate_awEmailTemplate", Storage="_awSite_EmailTemplate", ThisKey="siteId", OtherKey="siteId", IsForeignKey=true)]
		public awSite_EmailTemplate awSite_EmailTemplate
		{
			get
			{
				return this._awSite_EmailTemplate.Entity;
			}
			set
			{
				awSite_EmailTemplate previousValue = this._awSite_EmailTemplate.Entity;
				if (((previousValue != value) 
							|| (this._awSite_EmailTemplate.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._awSite_EmailTemplate.Entity = null;
						previousValue.awEmailTemplates.Remove(this);
					}
					this._awSite_EmailTemplate.Entity = value;
					if ((value != null))
					{
						value.awEmailTemplates.Add(this);
						this._siteId = value.siteId;
					}
					else
					{
						this._siteId = default(long);
					}
					this.SendPropertyChanged("awSite_EmailTemplate");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_awBlog_EmailTemplates(awBlog_EmailTemplate entity)
		{
			this.SendPropertyChanging();
			entity.awEmailTemplate = this;
		}
		
		private void detach_awBlog_EmailTemplates(awBlog_EmailTemplate entity)
		{
			this.SendPropertyChanging();
			entity.awEmailTemplate = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awBlog")]
	public partial class awBlog_EmailTemplate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _blogId;
		
		private long _siteId;
		
		private long _userId;
		
		private string _title;
		
		private string _description;
		
		private string _imageurl;
		
		private string _blogPostPage;
		
		private bool _isEnabled;
		
		private bool _enableCommentEmailNotifier;
		
		private string _commentEmailTo;
		
		private System.Nullable<long> _commentEmailTemplateId;
		
		private System.Nullable<System.DateTime> _lastBuildDate;
		
		private System.DateTime _createDate;
		
		private EntityRef<awEmailTemplate> _awEmailTemplate;
		
		private EntityRef<awSite_EmailTemplate> _awSite_EmailTemplate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnblogIdChanging(long value);
    partial void OnblogIdChanged();
    partial void OnsiteIdChanging(long value);
    partial void OnsiteIdChanged();
    partial void OnuserIdChanging(long value);
    partial void OnuserIdChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnimageurlChanging(string value);
    partial void OnimageurlChanged();
    partial void OnblogPostPageChanging(string value);
    partial void OnblogPostPageChanged();
    partial void OnisEnabledChanging(bool value);
    partial void OnisEnabledChanged();
    partial void OnenableCommentEmailNotifierChanging(bool value);
    partial void OnenableCommentEmailNotifierChanged();
    partial void OncommentEmailToChanging(string value);
    partial void OncommentEmailToChanged();
    partial void OncommentEmailTemplateIdChanging(System.Nullable<long> value);
    partial void OncommentEmailTemplateIdChanged();
    partial void OnlastBuildDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastBuildDateChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    #endregion
		
		public awBlog_EmailTemplate()
		{
			this._awEmailTemplate = default(EntityRef<awEmailTemplate>);
			this._awSite_EmailTemplate = default(EntityRef<awSite_EmailTemplate>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blogId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long blogId
		{
			get
			{
				return this._blogId;
			}
			set
			{
				if ((this._blogId != value))
				{
					this.OnblogIdChanging(value);
					this.SendPropertyChanging();
					this._blogId = value;
					this.SendPropertyChanged("blogId");
					this.OnblogIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="BigInt NOT NULL")]
		public long siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					if (this._awSite_EmailTemplate.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="BigInt NOT NULL")]
		public long userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(512)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageurl", DbType="NVarChar(255)")]
		public string imageurl
		{
			get
			{
				return this._imageurl;
			}
			set
			{
				if ((this._imageurl != value))
				{
					this.OnimageurlChanging(value);
					this.SendPropertyChanging();
					this._imageurl = value;
					this.SendPropertyChanged("imageurl");
					this.OnimageurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blogPostPage", DbType="VarChar(100)")]
		public string blogPostPage
		{
			get
			{
				return this._blogPostPage;
			}
			set
			{
				if ((this._blogPostPage != value))
				{
					this.OnblogPostPageChanging(value);
					this.SendPropertyChanging();
					this._blogPostPage = value;
					this.SendPropertyChanged("blogPostPage");
					this.OnblogPostPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isEnabled", DbType="Bit NOT NULL")]
		public bool isEnabled
		{
			get
			{
				return this._isEnabled;
			}
			set
			{
				if ((this._isEnabled != value))
				{
					this.OnisEnabledChanging(value);
					this.SendPropertyChanging();
					this._isEnabled = value;
					this.SendPropertyChanged("isEnabled");
					this.OnisEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enableCommentEmailNotifier", DbType="Bit NOT NULL")]
		public bool enableCommentEmailNotifier
		{
			get
			{
				return this._enableCommentEmailNotifier;
			}
			set
			{
				if ((this._enableCommentEmailNotifier != value))
				{
					this.OnenableCommentEmailNotifierChanging(value);
					this.SendPropertyChanging();
					this._enableCommentEmailNotifier = value;
					this.SendPropertyChanged("enableCommentEmailNotifier");
					this.OnenableCommentEmailNotifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commentEmailTo", DbType="NVarChar(100)")]
		public string commentEmailTo
		{
			get
			{
				return this._commentEmailTo;
			}
			set
			{
				if ((this._commentEmailTo != value))
				{
					this.OncommentEmailToChanging(value);
					this.SendPropertyChanging();
					this._commentEmailTo = value;
					this.SendPropertyChanged("commentEmailTo");
					this.OncommentEmailToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commentEmailTemplateId", DbType="BigInt")]
		public System.Nullable<long> commentEmailTemplateId
		{
			get
			{
				return this._commentEmailTemplateId;
			}
			set
			{
				if ((this._commentEmailTemplateId != value))
				{
					if (this._awEmailTemplate.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncommentEmailTemplateIdChanging(value);
					this.SendPropertyChanging();
					this._commentEmailTemplateId = value;
					this.SendPropertyChanged("commentEmailTemplateId");
					this.OncommentEmailTemplateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastBuildDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastBuildDate
		{
			get
			{
				return this._lastBuildDate;
			}
			set
			{
				if ((this._lastBuildDate != value))
				{
					this.OnlastBuildDateChanging(value);
					this.SendPropertyChanging();
					this._lastBuildDate = value;
					this.SendPropertyChanged("lastBuildDate");
					this.OnlastBuildDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awEmailTemplate_awBlog_EmailTemplate", Storage="_awEmailTemplate", ThisKey="commentEmailTemplateId", OtherKey="emailTemplateId", IsForeignKey=true)]
		public awEmailTemplate awEmailTemplate
		{
			get
			{
				return this._awEmailTemplate.Entity;
			}
			set
			{
				awEmailTemplate previousValue = this._awEmailTemplate.Entity;
				if (((previousValue != value) 
							|| (this._awEmailTemplate.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._awEmailTemplate.Entity = null;
						previousValue.awBlog_EmailTemplates.Remove(this);
					}
					this._awEmailTemplate.Entity = value;
					if ((value != null))
					{
						value.awBlog_EmailTemplates.Add(this);
						this._commentEmailTemplateId = value.emailTemplateId;
					}
					else
					{
						this._commentEmailTemplateId = default(Nullable<long>);
					}
					this.SendPropertyChanged("awEmailTemplate");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awSite_EmailTemplate_awBlog_EmailTemplate", Storage="_awSite_EmailTemplate", ThisKey="siteId", OtherKey="siteId", IsForeignKey=true)]
		public awSite_EmailTemplate awSite_EmailTemplate
		{
			get
			{
				return this._awSite_EmailTemplate.Entity;
			}
			set
			{
				awSite_EmailTemplate previousValue = this._awSite_EmailTemplate.Entity;
				if (((previousValue != value) 
							|| (this._awSite_EmailTemplate.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._awSite_EmailTemplate.Entity = null;
						previousValue.awBlog_EmailTemplates.Remove(this);
					}
					this._awSite_EmailTemplate.Entity = value;
					if ((value != null))
					{
						value.awBlog_EmailTemplates.Add(this);
						this._siteId = value.siteId;
					}
					else
					{
						this._siteId = default(long);
					}
					this.SendPropertyChanged("awSite_EmailTemplate");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
