#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWAPI_Data.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Awapi")]
	public partial class FileContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertawFileGroup(awFileGroup instance);
    partial void UpdateawFileGroup(awFileGroup instance);
    partial void DeleteawFileGroup(awFileGroup instance);
    partial void InsertawFileInGroup(awFileInGroup instance);
    partial void UpdateawFileInGroup(awFileInGroup instance);
    partial void DeleteawFileInGroup(awFileInGroup instance);
    partial void InsertawUser_File(awUser_File instance);
    partial void UpdateawUser_File(awUser_File instance);
    partial void DeleteawUser_File(awUser_File instance);
    partial void InsertawFile(awFile instance);
    partial void UpdateawFile(awFile instance);
    partial void DeleteawFile(awFile instance);
    #endregion
		
		public FileContextDataContext() : 
				base(global::AWAPI_Data.Properties.Settings.Default.AwapiConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public FileContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FileContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FileContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FileContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<awFileGroup> awFileGroups
		{
			get
			{
				return this.GetTable<awFileGroup>();
			}
		}
		
		public System.Data.Linq.Table<awFileInGroup> awFileInGroups
		{
			get
			{
				return this.GetTable<awFileInGroup>();
			}
		}
		
		public System.Data.Linq.Table<awUser_File> awUser_Files
		{
			get
			{
				return this.GetTable<awUser_File>();
			}
		}
		
		public System.Data.Linq.Table<awFile> awFiles
		{
			get
			{
				return this.GetTable<awFile>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awFileGroup")]
	public partial class awFileGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _fileGroupId;
		
		private string _title;
		
		private string _description;
		
		private System.Nullable<System.DateTime> _pubDate;
		
		private System.Nullable<System.DateTime> _lastBuildDate;
		
		private System.Nullable<long> _userId;
		
		private System.Nullable<long> _siteId;
		
		private System.DateTime _createDate;
		
		private EntitySet<awFileInGroup> _awFileInGroups;
		
		private EntityRef<awUser_File> _awUser_File;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfileGroupIdChanging(long value);
    partial void OnfileGroupIdChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnpubDateChanging(System.Nullable<System.DateTime> value);
    partial void OnpubDateChanged();
    partial void OnlastBuildDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastBuildDateChanged();
    partial void OnuserIdChanging(System.Nullable<long> value);
    partial void OnuserIdChanged();
    partial void OnsiteIdChanging(System.Nullable<long> value);
    partial void OnsiteIdChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    #endregion
		
		public awFileGroup()
		{
			this._awFileInGroups = new EntitySet<awFileInGroup>(new Action<awFileInGroup>(this.attach_awFileInGroups), new Action<awFileInGroup>(this.detach_awFileInGroups));
			this._awUser_File = default(EntityRef<awUser_File>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileGroupId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long fileGroupId
		{
			get
			{
				return this._fileGroupId;
			}
			set
			{
				if ((this._fileGroupId != value))
				{
					this.OnfileGroupIdChanging(value);
					this.SendPropertyChanging();
					this._fileGroupId = value;
					this.SendPropertyChanged("fileGroupId");
					this.OnfileGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(255)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pubDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> pubDate
		{
			get
			{
				return this._pubDate;
			}
			set
			{
				if ((this._pubDate != value))
				{
					this.OnpubDateChanging(value);
					this.SendPropertyChanging();
					this._pubDate = value;
					this.SendPropertyChanged("pubDate");
					this.OnpubDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastBuildDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastBuildDate
		{
			get
			{
				return this._lastBuildDate;
			}
			set
			{
				if ((this._lastBuildDate != value))
				{
					this.OnlastBuildDateChanging(value);
					this.SendPropertyChanging();
					this._lastBuildDate = value;
					this.SendPropertyChanged("lastBuildDate");
					this.OnlastBuildDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="BigInt")]
		public System.Nullable<long> userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._awUser_File.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="BigInt")]
		public System.Nullable<long> siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awFileGroup_awFileInGroup", Storage="_awFileInGroups", ThisKey="fileGroupId", OtherKey="fileGroupId")]
		public EntitySet<awFileInGroup> awFileInGroups
		{
			get
			{
				return this._awFileInGroups;
			}
			set
			{
				this._awFileInGroups.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awUser_File_awFileGroup", Storage="_awUser_File", ThisKey="userId", OtherKey="userId", IsForeignKey=true)]
		public awUser_File awUser_File
		{
			get
			{
				return this._awUser_File.Entity;
			}
			set
			{
				awUser_File previousValue = this._awUser_File.Entity;
				if (((previousValue != value) 
							|| (this._awUser_File.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._awUser_File.Entity = null;
						previousValue.awFileGroups.Remove(this);
					}
					this._awUser_File.Entity = value;
					if ((value != null))
					{
						value.awFileGroups.Add(this);
						this._userId = value.userId;
					}
					else
					{
						this._userId = default(Nullable<long>);
					}
					this.SendPropertyChanged("awUser_File");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_awFileInGroups(awFileInGroup entity)
		{
			this.SendPropertyChanging();
			entity.awFileGroup = this;
		}
		
		private void detach_awFileInGroups(awFileInGroup entity)
		{
			this.SendPropertyChanging();
			entity.awFileGroup = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awFileInGroup")]
	public partial class awFileInGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _fileInGroupId;
		
		private long _fileGroupId;
		
		private long _fileId;
		
		private System.DateTime _createDate;
		
		private EntityRef<awFileGroup> _awFileGroup;
		
		private EntityRef<awFile> _awFile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfileInGroupIdChanging(long value);
    partial void OnfileInGroupIdChanged();
    partial void OnfileGroupIdChanging(long value);
    partial void OnfileGroupIdChanged();
    partial void OnfileIdChanging(long value);
    partial void OnfileIdChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    #endregion
		
		public awFileInGroup()
		{
			this._awFileGroup = default(EntityRef<awFileGroup>);
			this._awFile = default(EntityRef<awFile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileInGroupId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long fileInGroupId
		{
			get
			{
				return this._fileInGroupId;
			}
			set
			{
				if ((this._fileInGroupId != value))
				{
					this.OnfileInGroupIdChanging(value);
					this.SendPropertyChanging();
					this._fileInGroupId = value;
					this.SendPropertyChanged("fileInGroupId");
					this.OnfileInGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileGroupId", DbType="BigInt NOT NULL")]
		public long fileGroupId
		{
			get
			{
				return this._fileGroupId;
			}
			set
			{
				if ((this._fileGroupId != value))
				{
					if (this._awFileGroup.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfileGroupIdChanging(value);
					this.SendPropertyChanging();
					this._fileGroupId = value;
					this.SendPropertyChanged("fileGroupId");
					this.OnfileGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileId", DbType="BigInt NOT NULL")]
		public long fileId
		{
			get
			{
				return this._fileId;
			}
			set
			{
				if ((this._fileId != value))
				{
					if (this._awFile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfileIdChanging(value);
					this.SendPropertyChanging();
					this._fileId = value;
					this.SendPropertyChanged("fileId");
					this.OnfileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awFileGroup_awFileInGroup", Storage="_awFileGroup", ThisKey="fileGroupId", OtherKey="fileGroupId", IsForeignKey=true)]
		public awFileGroup awFileGroup
		{
			get
			{
				return this._awFileGroup.Entity;
			}
			set
			{
				awFileGroup previousValue = this._awFileGroup.Entity;
				if (((previousValue != value) 
							|| (this._awFileGroup.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._awFileGroup.Entity = null;
						previousValue.awFileInGroups.Remove(this);
					}
					this._awFileGroup.Entity = value;
					if ((value != null))
					{
						value.awFileInGroups.Add(this);
						this._fileGroupId = value.fileGroupId;
					}
					else
					{
						this._fileGroupId = default(long);
					}
					this.SendPropertyChanged("awFileGroup");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awFile_awFileInGroup", Storage="_awFile", ThisKey="fileId", OtherKey="fileId", IsForeignKey=true)]
		public awFile awFile
		{
			get
			{
				return this._awFile.Entity;
			}
			set
			{
				awFile previousValue = this._awFile.Entity;
				if (((previousValue != value) 
							|| (this._awFile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._awFile.Entity = null;
						previousValue.awFileInGroups.Remove(this);
					}
					this._awFile.Entity = value;
					if ((value != null))
					{
						value.awFileInGroups.Add(this);
						this._fileId = value.fileId;
					}
					else
					{
						this._fileId = default(long);
					}
					this.SendPropertyChanged("awFile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awUser")]
	public partial class awUser_File : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _userId;
		
		private string _username;
		
		private string _email;
		
		private string _password;
		
		private string _firstName;
		
		private string _lastName;
		
		private bool _isSuperAdmin;
		
		private bool _isEnabled;
		
		private bool _isDeleted;
		
		private string _imageurl;
		
		private string _link;
		
		private string _description;
		
		private string _gender;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _tel;
		
		private string _tel2;
		
		private string _fax;
		
		private string _address;
		
		private string _city;
		
		private string _state;
		
		private string _postalcode;
		
		private string _country;
		
		private System.Nullable<System.DateTime> _lastBuildDate;
		
		private System.DateTime _createDate;
		
		private EntitySet<awFileGroup> _awFileGroups;
		
		private EntitySet<awFile> _awFiles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIdChanging(long value);
    partial void OnuserIdChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnisSuperAdminChanging(bool value);
    partial void OnisSuperAdminChanged();
    partial void OnisEnabledChanging(bool value);
    partial void OnisEnabledChanged();
    partial void OnisDeletedChanging(bool value);
    partial void OnisDeletedChanged();
    partial void OnimageurlChanging(string value);
    partial void OnimageurlChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void Ontel2Changing(string value);
    partial void Ontel2Changed();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OnpostalcodeChanging(string value);
    partial void OnpostalcodeChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnlastBuildDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastBuildDateChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    #endregion
		
		public awUser_File()
		{
			this._awFileGroups = new EntitySet<awFileGroup>(new Action<awFileGroup>(this.attach_awFileGroups), new Action<awFileGroup>(this.detach_awFileGroups));
			this._awFiles = new EntitySet<awFile>(new Action<awFile>(this.attach_awFiles), new Action<awFile>(this.detach_awFiles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this.OnfirstNameChanging(value);
					this.SendPropertyChanging();
					this._firstName = value;
					this.SendPropertyChanged("firstName");
					this.OnfirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this.OnlastNameChanging(value);
					this.SendPropertyChanging();
					this._lastName = value;
					this.SendPropertyChanged("lastName");
					this.OnlastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSuperAdmin", DbType="Bit NOT NULL")]
		public bool isSuperAdmin
		{
			get
			{
				return this._isSuperAdmin;
			}
			set
			{
				if ((this._isSuperAdmin != value))
				{
					this.OnisSuperAdminChanging(value);
					this.SendPropertyChanging();
					this._isSuperAdmin = value;
					this.SendPropertyChanged("isSuperAdmin");
					this.OnisSuperAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isEnabled", DbType="Bit NOT NULL")]
		public bool isEnabled
		{
			get
			{
				return this._isEnabled;
			}
			set
			{
				if ((this._isEnabled != value))
				{
					this.OnisEnabledChanging(value);
					this.SendPropertyChanging();
					this._isEnabled = value;
					this.SendPropertyChanged("isEnabled");
					this.OnisEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDeleted", DbType="Bit NOT NULL")]
		public bool isDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if ((this._isDeleted != value))
				{
					this.OnisDeletedChanging(value);
					this.SendPropertyChanging();
					this._isDeleted = value;
					this.SendPropertyChanged("isDeleted");
					this.OnisDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageurl", DbType="NVarChar(255)")]
		public string imageurl
		{
			get
			{
				return this._imageurl;
			}
			set
			{
				if ((this._imageurl != value))
				{
					this.OnimageurlChanging(value);
					this.SendPropertyChanging();
					this._imageurl = value;
					this.SendPropertyChanged("imageurl");
					this.OnimageurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(255)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(2)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="VarChar(50)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel2", DbType="VarChar(50)")]
		public string tel2
		{
			get
			{
				return this._tel2;
			}
			set
			{
				if ((this._tel2 != value))
				{
					this.Ontel2Changing(value);
					this.SendPropertyChanging();
					this._tel2 = value;
					this.SendPropertyChanged("tel2");
					this.Ontel2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(50)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(255)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="NVarChar(50)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postalcode", DbType="NVarChar(20)")]
		public string postalcode
		{
			get
			{
				return this._postalcode;
			}
			set
			{
				if ((this._postalcode != value))
				{
					this.OnpostalcodeChanging(value);
					this.SendPropertyChanging();
					this._postalcode = value;
					this.SendPropertyChanged("postalcode");
					this.OnpostalcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(50)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastBuildDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastBuildDate
		{
			get
			{
				return this._lastBuildDate;
			}
			set
			{
				if ((this._lastBuildDate != value))
				{
					this.OnlastBuildDateChanging(value);
					this.SendPropertyChanging();
					this._lastBuildDate = value;
					this.SendPropertyChanged("lastBuildDate");
					this.OnlastBuildDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awUser_File_awFileGroup", Storage="_awFileGroups", ThisKey="userId", OtherKey="userId")]
		public EntitySet<awFileGroup> awFileGroups
		{
			get
			{
				return this._awFileGroups;
			}
			set
			{
				this._awFileGroups.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awUser_File_awFile", Storage="_awFiles", ThisKey="userId", OtherKey="userId")]
		public EntitySet<awFile> awFiles
		{
			get
			{
				return this._awFiles;
			}
			set
			{
				this._awFiles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_awFileGroups(awFileGroup entity)
		{
			this.SendPropertyChanging();
			entity.awUser_File = this;
		}
		
		private void detach_awFileGroups(awFileGroup entity)
		{
			this.SendPropertyChanging();
			entity.awUser_File = null;
		}
		
		private void attach_awFiles(awFile entity)
		{
			this.SendPropertyChanging();
			entity.awUser_File = this;
		}
		
		private void detach_awFiles(awFile entity)
		{
			this.SendPropertyChanging();
			entity.awUser_File = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awFile")]
	public partial class awFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _fileId;
		
		private long _siteId;
		
		private string _title;
		
		private string _description;
		
		private string _path;
		
		private string _thumbnail;
		
		private string _contentType;
		
		private int _contentSize;
		
		private string _link;
		
		private System.Nullable<System.DateTime> _pubDate;
		
		private System.Nullable<System.DateTime> _lastBuildDate;
		
		private bool _isEnabled;
		
		private bool _isOnLocal;
		
		private System.Nullable<long> _userId;
		
		private System.DateTime _createDate;
		
		private EntitySet<awFileInGroup> _awFileInGroups;
		
		private EntityRef<awUser_File> _awUser_File;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfileIdChanging(long value);
    partial void OnfileIdChanged();
    partial void OnsiteIdChanging(long value);
    partial void OnsiteIdChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnpathChanging(string value);
    partial void OnpathChanged();
    partial void OnthumbnailChanging(string value);
    partial void OnthumbnailChanged();
    partial void OncontentTypeChanging(string value);
    partial void OncontentTypeChanged();
    partial void OncontentSizeChanging(int value);
    partial void OncontentSizeChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnpubDateChanging(System.Nullable<System.DateTime> value);
    partial void OnpubDateChanged();
    partial void OnlastBuildDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastBuildDateChanged();
    partial void OnisEnabledChanging(bool value);
    partial void OnisEnabledChanged();
    partial void OnisOnLocalChanging(bool value);
    partial void OnisOnLocalChanged();
    partial void OnuserIdChanging(System.Nullable<long> value);
    partial void OnuserIdChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    #endregion
		
		public awFile()
		{
			this._awFileInGroups = new EntitySet<awFileInGroup>(new Action<awFileInGroup>(this.attach_awFileInGroups), new Action<awFileInGroup>(this.detach_awFileInGroups));
			this._awUser_File = default(EntityRef<awUser_File>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long fileId
		{
			get
			{
				return this._fileId;
			}
			set
			{
				if ((this._fileId != value))
				{
					this.OnfileIdChanging(value);
					this.SendPropertyChanging();
					this._fileId = value;
					this.SendPropertyChanged("fileId");
					this.OnfileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="BigInt NOT NULL")]
		public long siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(512)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_path", DbType="NVarChar(512)")]
		public string path
		{
			get
			{
				return this._path;
			}
			set
			{
				if ((this._path != value))
				{
					this.OnpathChanging(value);
					this.SendPropertyChanging();
					this._path = value;
					this.SendPropertyChanged("path");
					this.OnpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thumbnail", DbType="NVarChar(512)")]
		public string thumbnail
		{
			get
			{
				return this._thumbnail;
			}
			set
			{
				if ((this._thumbnail != value))
				{
					this.OnthumbnailChanging(value);
					this.SendPropertyChanging();
					this._thumbnail = value;
					this.SendPropertyChanged("thumbnail");
					this.OnthumbnailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contentType", DbType="NVarChar(100)")]
		public string contentType
		{
			get
			{
				return this._contentType;
			}
			set
			{
				if ((this._contentType != value))
				{
					this.OncontentTypeChanging(value);
					this.SendPropertyChanging();
					this._contentType = value;
					this.SendPropertyChanged("contentType");
					this.OncontentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contentSize", DbType="Int NOT NULL")]
		public int contentSize
		{
			get
			{
				return this._contentSize;
			}
			set
			{
				if ((this._contentSize != value))
				{
					this.OncontentSizeChanging(value);
					this.SendPropertyChanging();
					this._contentSize = value;
					this.SendPropertyChanged("contentSize");
					this.OncontentSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(255)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pubDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> pubDate
		{
			get
			{
				return this._pubDate;
			}
			set
			{
				if ((this._pubDate != value))
				{
					this.OnpubDateChanging(value);
					this.SendPropertyChanging();
					this._pubDate = value;
					this.SendPropertyChanged("pubDate");
					this.OnpubDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastBuildDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastBuildDate
		{
			get
			{
				return this._lastBuildDate;
			}
			set
			{
				if ((this._lastBuildDate != value))
				{
					this.OnlastBuildDateChanging(value);
					this.SendPropertyChanging();
					this._lastBuildDate = value;
					this.SendPropertyChanged("lastBuildDate");
					this.OnlastBuildDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isEnabled", DbType="Bit NOT NULL")]
		public bool isEnabled
		{
			get
			{
				return this._isEnabled;
			}
			set
			{
				if ((this._isEnabled != value))
				{
					this.OnisEnabledChanging(value);
					this.SendPropertyChanging();
					this._isEnabled = value;
					this.SendPropertyChanged("isEnabled");
					this.OnisEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isOnLocal", DbType="Bit NOT NULL")]
		public bool isOnLocal
		{
			get
			{
				return this._isOnLocal;
			}
			set
			{
				if ((this._isOnLocal != value))
				{
					this.OnisOnLocalChanging(value);
					this.SendPropertyChanging();
					this._isOnLocal = value;
					this.SendPropertyChanged("isOnLocal");
					this.OnisOnLocalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="BigInt")]
		public System.Nullable<long> userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._awUser_File.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awFile_awFileInGroup", Storage="_awFileInGroups", ThisKey="fileId", OtherKey="fileId")]
		public EntitySet<awFileInGroup> awFileInGroups
		{
			get
			{
				return this._awFileInGroups;
			}
			set
			{
				this._awFileInGroups.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awUser_File_awFile", Storage="_awUser_File", ThisKey="userId", OtherKey="userId", IsForeignKey=true)]
		public awUser_File awUser_File
		{
			get
			{
				return this._awUser_File.Entity;
			}
			set
			{
				awUser_File previousValue = this._awUser_File.Entity;
				if (((previousValue != value) 
							|| (this._awUser_File.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._awUser_File.Entity = null;
						previousValue.awFiles.Remove(this);
					}
					this._awUser_File.Entity = value;
					if ((value != null))
					{
						value.awFiles.Add(this);
						this._userId = value.userId;
					}
					else
					{
						this._userId = default(Nullable<long>);
					}
					this.SendPropertyChanged("awUser_File");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_awFileInGroups(awFileInGroup entity)
		{
			this.SendPropertyChanging();
			entity.awFile = this;
		}
		
		private void detach_awFileInGroups(awFileInGroup entity)
		{
			this.SendPropertyChanging();
			entity.awFile = null;
		}
	}
}
#pragma warning restore 1591
