#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWAPI_Data.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Awapi")]
	public partial class PollContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertawSite_Poll(awSite_Poll instance);
    partial void UpdateawSite_Poll(awSite_Poll instance);
    partial void DeleteawSite_Poll(awSite_Poll instance);
    partial void InsertawPoll(awPoll instance);
    partial void UpdateawPoll(awPoll instance);
    partial void DeleteawPoll(awPoll instance);
    partial void InsertawPollChoice(awPollChoice instance);
    partial void UpdateawPollChoice(awPollChoice instance);
    partial void DeleteawPollChoice(awPollChoice instance);
    #endregion
		
		public PollContextDataContext() : 
				base(global::AWAPI_Data.Properties.Settings.Default.AWAPIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PollContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PollContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PollContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PollContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<awSite_Poll> awSite_Polls
		{
			get
			{
				return this.GetTable<awSite_Poll>();
			}
		}
		
		public System.Data.Linq.Table<awPoll> awPolls
		{
			get
			{
				return this.GetTable<awPoll>();
			}
		}
		
		public System.Data.Linq.Table<awPollChoice> awPollChoices
		{
			get
			{
				return this.GetTable<awPollChoice>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awSite")]
	public partial class awSite_Poll : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _siteId;
		
		private string _alias;
		
		private string _title;
		
		private string _description;
		
		private bool _isEnabled;
		
		private string _cultureCode;
		
		private string _link;
		
		private string _imageurl;
		
		private System.Nullable<System.DateTime> _pubDate;
		
		private int _maxBlogs;
		
		private int _maxUsers;
		
		private int _maxContents;
		
		private string _accessKey;
		
		private string _grantedDomains;
		
		private string _bannedDomains;
		
		private System.Nullable<long> _userId;
		
		private System.Nullable<System.DateTime> _lastBuildDate;
		
		private System.Nullable<System.DateTime> _createDate;
		
		private EntitySet<awPoll> _awPolls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsiteIdChanging(long value);
    partial void OnsiteIdChanged();
    partial void OnaliasChanging(string value);
    partial void OnaliasChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnisEnabledChanging(bool value);
    partial void OnisEnabledChanged();
    partial void OncultureCodeChanging(string value);
    partial void OncultureCodeChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnimageurlChanging(string value);
    partial void OnimageurlChanged();
    partial void OnpubDateChanging(System.Nullable<System.DateTime> value);
    partial void OnpubDateChanged();
    partial void OnmaxBlogsChanging(int value);
    partial void OnmaxBlogsChanged();
    partial void OnmaxUsersChanging(int value);
    partial void OnmaxUsersChanged();
    partial void OnmaxContentsChanging(int value);
    partial void OnmaxContentsChanged();
    partial void OnaccessKeyChanging(string value);
    partial void OnaccessKeyChanged();
    partial void OngrantedDomainsChanging(string value);
    partial void OngrantedDomainsChanged();
    partial void OnbannedDomainsChanging(string value);
    partial void OnbannedDomainsChanged();
    partial void OnuserIdChanging(System.Nullable<long> value);
    partial void OnuserIdChanged();
    partial void OnlastBuildDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastBuildDateChanged();
    partial void OncreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreateDateChanged();
    #endregion
		
		public awSite_Poll()
		{
			this._awPolls = new EntitySet<awPoll>(new Action<awPoll>(this.attach_awPolls), new Action<awPoll>(this.detach_awPolls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alias", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				if ((this._alias != value))
				{
					this.OnaliasChanging(value);
					this.SendPropertyChanging();
					this._alias = value;
					this.SendPropertyChanged("alias");
					this.OnaliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(512)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isEnabled", DbType="Bit NOT NULL")]
		public bool isEnabled
		{
			get
			{
				return this._isEnabled;
			}
			set
			{
				if ((this._isEnabled != value))
				{
					this.OnisEnabledChanging(value);
					this.SendPropertyChanging();
					this._isEnabled = value;
					this.SendPropertyChanged("isEnabled");
					this.OnisEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cultureCode", DbType="NVarChar(2)")]
		public string cultureCode
		{
			get
			{
				return this._cultureCode;
			}
			set
			{
				if ((this._cultureCode != value))
				{
					this.OncultureCodeChanging(value);
					this.SendPropertyChanging();
					this._cultureCode = value;
					this.SendPropertyChanged("cultureCode");
					this.OncultureCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(255)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageurl", DbType="NVarChar(255)")]
		public string imageurl
		{
			get
			{
				return this._imageurl;
			}
			set
			{
				if ((this._imageurl != value))
				{
					this.OnimageurlChanging(value);
					this.SendPropertyChanging();
					this._imageurl = value;
					this.SendPropertyChanged("imageurl");
					this.OnimageurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pubDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> pubDate
		{
			get
			{
				return this._pubDate;
			}
			set
			{
				if ((this._pubDate != value))
				{
					this.OnpubDateChanging(value);
					this.SendPropertyChanging();
					this._pubDate = value;
					this.SendPropertyChanged("pubDate");
					this.OnpubDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxBlogs", DbType="Int NOT NULL")]
		public int maxBlogs
		{
			get
			{
				return this._maxBlogs;
			}
			set
			{
				if ((this._maxBlogs != value))
				{
					this.OnmaxBlogsChanging(value);
					this.SendPropertyChanging();
					this._maxBlogs = value;
					this.SendPropertyChanged("maxBlogs");
					this.OnmaxBlogsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxUsers", DbType="Int NOT NULL")]
		public int maxUsers
		{
			get
			{
				return this._maxUsers;
			}
			set
			{
				if ((this._maxUsers != value))
				{
					this.OnmaxUsersChanging(value);
					this.SendPropertyChanging();
					this._maxUsers = value;
					this.SendPropertyChanged("maxUsers");
					this.OnmaxUsersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxContents", DbType="Int NOT NULL")]
		public int maxContents
		{
			get
			{
				return this._maxContents;
			}
			set
			{
				if ((this._maxContents != value))
				{
					this.OnmaxContentsChanging(value);
					this.SendPropertyChanging();
					this._maxContents = value;
					this.SendPropertyChanged("maxContents");
					this.OnmaxContentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accessKey", DbType="VarChar(50)")]
		public string accessKey
		{
			get
			{
				return this._accessKey;
			}
			set
			{
				if ((this._accessKey != value))
				{
					this.OnaccessKeyChanging(value);
					this.SendPropertyChanging();
					this._accessKey = value;
					this.SendPropertyChanged("accessKey");
					this.OnaccessKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grantedDomains", DbType="VarChar(512)")]
		public string grantedDomains
		{
			get
			{
				return this._grantedDomains;
			}
			set
			{
				if ((this._grantedDomains != value))
				{
					this.OngrantedDomainsChanging(value);
					this.SendPropertyChanging();
					this._grantedDomains = value;
					this.SendPropertyChanged("grantedDomains");
					this.OngrantedDomainsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bannedDomains", DbType="VarChar(512)")]
		public string bannedDomains
		{
			get
			{
				return this._bannedDomains;
			}
			set
			{
				if ((this._bannedDomains != value))
				{
					this.OnbannedDomainsChanging(value);
					this.SendPropertyChanging();
					this._bannedDomains = value;
					this.SendPropertyChanged("bannedDomains");
					this.OnbannedDomainsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="BigInt")]
		public System.Nullable<long> userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastBuildDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastBuildDate
		{
			get
			{
				return this._lastBuildDate;
			}
			set
			{
				if ((this._lastBuildDate != value))
				{
					this.OnlastBuildDateChanging(value);
					this.SendPropertyChanging();
					this._lastBuildDate = value;
					this.SendPropertyChanged("lastBuildDate");
					this.OnlastBuildDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awSite_Poll_awPoll", Storage="_awPolls", ThisKey="siteId", OtherKey="siteId")]
		public EntitySet<awPoll> awPolls
		{
			get
			{
				return this._awPolls;
			}
			set
			{
				this._awPolls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_awPolls(awPoll entity)
		{
			this.SendPropertyChanging();
			entity.awSite_Poll = this;
		}
		
		private void detach_awPolls(awPoll entity)
		{
			this.SendPropertyChanging();
			entity.awSite_Poll = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awPoll")]
	public partial class awPoll : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _pollId;
		
		private long _siteId;
		
		private long _userId;
		
		private string _title;
		
		private string _description;
		
		private string _answeredQuestion;
		
		private bool _isEnabled;
		
		private bool _isPublic;
		
		private bool _isMultipleChoice;
		
		private System.Nullable<System.DateTime> _pubDate;
		
		private System.Nullable<System.DateTime> _pubEndDate;
		
		private System.Nullable<System.DateTime> _lastBuildDate;
		
		private System.DateTime _createDate;
		
		private EntitySet<awPollChoice> _awPollChoices;
		
		private EntityRef<awSite_Poll> _awSite_Poll;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpollIdChanging(long value);
    partial void OnpollIdChanged();
    partial void OnsiteIdChanging(long value);
    partial void OnsiteIdChanged();
    partial void OnuserIdChanging(long value);
    partial void OnuserIdChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnansweredQuestionChanging(string value);
    partial void OnansweredQuestionChanged();
    partial void OnisEnabledChanging(bool value);
    partial void OnisEnabledChanged();
    partial void OnisPublicChanging(bool value);
    partial void OnisPublicChanged();
    partial void OnisMultipleChoiceChanging(bool value);
    partial void OnisMultipleChoiceChanged();
    partial void OnpubDateChanging(System.Nullable<System.DateTime> value);
    partial void OnpubDateChanged();
    partial void OnpubEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnpubEndDateChanged();
    partial void OnlastBuildDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastBuildDateChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    #endregion
		
		public awPoll()
		{
			this._awPollChoices = new EntitySet<awPollChoice>(new Action<awPollChoice>(this.attach_awPollChoices), new Action<awPollChoice>(this.detach_awPollChoices));
			this._awSite_Poll = default(EntityRef<awSite_Poll>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pollId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long pollId
		{
			get
			{
				return this._pollId;
			}
			set
			{
				if ((this._pollId != value))
				{
					this.OnpollIdChanging(value);
					this.SendPropertyChanging();
					this._pollId = value;
					this.SendPropertyChanged("pollId");
					this.OnpollIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="BigInt NOT NULL")]
		public long siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					if (this._awSite_Poll.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="BigInt NOT NULL")]
		public long userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(512)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answeredQuestion", DbType="NVarChar(512)")]
		public string answeredQuestion
		{
			get
			{
				return this._answeredQuestion;
			}
			set
			{
				if ((this._answeredQuestion != value))
				{
					this.OnansweredQuestionChanging(value);
					this.SendPropertyChanging();
					this._answeredQuestion = value;
					this.SendPropertyChanged("answeredQuestion");
					this.OnansweredQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isEnabled", DbType="Bit NOT NULL")]
		public bool isEnabled
		{
			get
			{
				return this._isEnabled;
			}
			set
			{
				if ((this._isEnabled != value))
				{
					this.OnisEnabledChanging(value);
					this.SendPropertyChanging();
					this._isEnabled = value;
					this.SendPropertyChanged("isEnabled");
					this.OnisEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isPublic", DbType="Bit NOT NULL")]
		public bool isPublic
		{
			get
			{
				return this._isPublic;
			}
			set
			{
				if ((this._isPublic != value))
				{
					this.OnisPublicChanging(value);
					this.SendPropertyChanging();
					this._isPublic = value;
					this.SendPropertyChanged("isPublic");
					this.OnisPublicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isMultipleChoice", DbType="Bit NOT NULL")]
		public bool isMultipleChoice
		{
			get
			{
				return this._isMultipleChoice;
			}
			set
			{
				if ((this._isMultipleChoice != value))
				{
					this.OnisMultipleChoiceChanging(value);
					this.SendPropertyChanging();
					this._isMultipleChoice = value;
					this.SendPropertyChanged("isMultipleChoice");
					this.OnisMultipleChoiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pubDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> pubDate
		{
			get
			{
				return this._pubDate;
			}
			set
			{
				if ((this._pubDate != value))
				{
					this.OnpubDateChanging(value);
					this.SendPropertyChanging();
					this._pubDate = value;
					this.SendPropertyChanged("pubDate");
					this.OnpubDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pubEndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> pubEndDate
		{
			get
			{
				return this._pubEndDate;
			}
			set
			{
				if ((this._pubEndDate != value))
				{
					this.OnpubEndDateChanging(value);
					this.SendPropertyChanging();
					this._pubEndDate = value;
					this.SendPropertyChanged("pubEndDate");
					this.OnpubEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastBuildDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastBuildDate
		{
			get
			{
				return this._lastBuildDate;
			}
			set
			{
				if ((this._lastBuildDate != value))
				{
					this.OnlastBuildDateChanging(value);
					this.SendPropertyChanging();
					this._lastBuildDate = value;
					this.SendPropertyChanged("lastBuildDate");
					this.OnlastBuildDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awPoll_awPollChoice", Storage="_awPollChoices", ThisKey="pollId", OtherKey="pollId")]
		public EntitySet<awPollChoice> awPollChoices
		{
			get
			{
				return this._awPollChoices;
			}
			set
			{
				this._awPollChoices.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awSite_Poll_awPoll", Storage="_awSite_Poll", ThisKey="siteId", OtherKey="siteId", IsForeignKey=true)]
		public awSite_Poll awSite_Poll
		{
			get
			{
				return this._awSite_Poll.Entity;
			}
			set
			{
				awSite_Poll previousValue = this._awSite_Poll.Entity;
				if (((previousValue != value) 
							|| (this._awSite_Poll.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._awSite_Poll.Entity = null;
						previousValue.awPolls.Remove(this);
					}
					this._awSite_Poll.Entity = value;
					if ((value != null))
					{
						value.awPolls.Add(this);
						this._siteId = value.siteId;
					}
					else
					{
						this._siteId = default(long);
					}
					this.SendPropertyChanged("awSite_Poll");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_awPollChoices(awPollChoice entity)
		{
			this.SendPropertyChanging();
			entity.awPoll = this;
		}
		
		private void detach_awPollChoices(awPollChoice entity)
		{
			this.SendPropertyChanging();
			entity.awPoll = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awPollChoice")]
	public partial class awPollChoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _pollChoiceId;
		
		private long _pollId;
		
		private string _title;
		
		private string _description;
		
		private int _numberOfVotes;
		
		private int _sortOrder;
		
		private System.Nullable<System.DateTime> _lastBuildDate;
		
		private System.DateTime _createDate;
		
		private EntityRef<awPoll> _awPoll;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpollChoiceIdChanging(long value);
    partial void OnpollChoiceIdChanged();
    partial void OnpollIdChanging(long value);
    partial void OnpollIdChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnnumberOfVotesChanging(int value);
    partial void OnnumberOfVotesChanged();
    partial void OnsortOrderChanging(int value);
    partial void OnsortOrderChanged();
    partial void OnlastBuildDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastBuildDateChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    #endregion
		
		public awPollChoice()
		{
			this._awPoll = default(EntityRef<awPoll>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pollChoiceId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long pollChoiceId
		{
			get
			{
				return this._pollChoiceId;
			}
			set
			{
				if ((this._pollChoiceId != value))
				{
					this.OnpollChoiceIdChanging(value);
					this.SendPropertyChanging();
					this._pollChoiceId = value;
					this.SendPropertyChanged("pollChoiceId");
					this.OnpollChoiceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pollId", DbType="BigInt NOT NULL")]
		public long pollId
		{
			get
			{
				return this._pollId;
			}
			set
			{
				if ((this._pollId != value))
				{
					if (this._awPoll.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpollIdChanging(value);
					this.SendPropertyChanging();
					this._pollId = value;
					this.SendPropertyChanged("pollId");
					this.OnpollIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(255)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numberOfVotes", DbType="Int NOT NULL")]
		public int numberOfVotes
		{
			get
			{
				return this._numberOfVotes;
			}
			set
			{
				if ((this._numberOfVotes != value))
				{
					this.OnnumberOfVotesChanging(value);
					this.SendPropertyChanging();
					this._numberOfVotes = value;
					this.SendPropertyChanged("numberOfVotes");
					this.OnnumberOfVotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sortOrder", DbType="Int NOT NULL")]
		public int sortOrder
		{
			get
			{
				return this._sortOrder;
			}
			set
			{
				if ((this._sortOrder != value))
				{
					this.OnsortOrderChanging(value);
					this.SendPropertyChanging();
					this._sortOrder = value;
					this.SendPropertyChanged("sortOrder");
					this.OnsortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastBuildDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastBuildDate
		{
			get
			{
				return this._lastBuildDate;
			}
			set
			{
				if ((this._lastBuildDate != value))
				{
					this.OnlastBuildDateChanging(value);
					this.SendPropertyChanging();
					this._lastBuildDate = value;
					this.SendPropertyChanged("lastBuildDate");
					this.OnlastBuildDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awPoll_awPollChoice", Storage="_awPoll", ThisKey="pollId", OtherKey="pollId", IsForeignKey=true)]
		public awPoll awPoll
		{
			get
			{
				return this._awPoll.Entity;
			}
			set
			{
				awPoll previousValue = this._awPoll.Entity;
				if (((previousValue != value) 
							|| (this._awPoll.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._awPoll.Entity = null;
						previousValue.awPollChoices.Remove(this);
					}
					this._awPoll.Entity = value;
					if ((value != null))
					{
						value.awPollChoices.Add(this);
						this._pollId = value.pollId;
					}
					else
					{
						this._pollId = default(long);
					}
					this.SendPropertyChanged("awPoll");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
