#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWAPI_Data.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AwapiCMS")]
	public partial class ShareItContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertawShareItWith(awShareItWith instance);
    partial void UpdateawShareItWith(awShareItWith instance);
    partial void DeleteawShareItWith(awShareItWith instance);
    partial void InsertawUser_ShareIt(awUser_ShareIt instance);
    partial void UpdateawUser_ShareIt(awUser_ShareIt instance);
    partial void DeleteawUser_ShareIt(awUser_ShareIt instance);
    partial void InsertawSite_ShareIt(awSite_ShareIt instance);
    partial void UpdateawSite_ShareIt(awSite_ShareIt instance);
    partial void DeleteawSite_ShareIt(awSite_ShareIt instance);
    partial void InsertawShareIt(awShareIt instance);
    partial void UpdateawShareIt(awShareIt instance);
    partial void DeleteawShareIt(awShareIt instance);
    #endregion
		
		public ShareItContextDataContext() : 
				base(global::AWAPI_Data.Properties.Settings.Default.AWAPIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ShareItContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShareItContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShareItContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShareItContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<awShareItWith> awShareItWiths
		{
			get
			{
				return this.GetTable<awShareItWith>();
			}
		}
		
		public System.Data.Linq.Table<awUser_ShareIt> awUser_ShareIts
		{
			get
			{
				return this.GetTable<awUser_ShareIt>();
			}
		}
		
		public System.Data.Linq.Table<awSite_ShareIt> awSite_ShareIts
		{
			get
			{
				return this.GetTable<awSite_ShareIt>();
			}
		}
		
		public System.Data.Linq.Table<awShareIt> awShareIts
		{
			get
			{
				return this.GetTable<awShareIt>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awShareItWith")]
	public partial class awShareItWith : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _shareItWithId;
		
		private long _shareItId;
		
		private long _userId;
		
		private System.DateTime _createDate;
		
		private EntityRef<awUser_ShareIt> _awUser_ShareIt;
		
		private EntityRef<awShareIt> _awShareIt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnshareItWithIdChanging(long value);
    partial void OnshareItWithIdChanged();
    partial void OnshareItIdChanging(long value);
    partial void OnshareItIdChanged();
    partial void OnuserIdChanging(long value);
    partial void OnuserIdChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    #endregion
		
		public awShareItWith()
		{
			this._awUser_ShareIt = default(EntityRef<awUser_ShareIt>);
			this._awShareIt = default(EntityRef<awShareIt>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shareItWithId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long shareItWithId
		{
			get
			{
				return this._shareItWithId;
			}
			set
			{
				if ((this._shareItWithId != value))
				{
					this.OnshareItWithIdChanging(value);
					this.SendPropertyChanging();
					this._shareItWithId = value;
					this.SendPropertyChanged("shareItWithId");
					this.OnshareItWithIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shareItId", DbType="BigInt NOT NULL")]
		public long shareItId
		{
			get
			{
				return this._shareItId;
			}
			set
			{
				if ((this._shareItId != value))
				{
					if (this._awShareIt.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnshareItIdChanging(value);
					this.SendPropertyChanging();
					this._shareItId = value;
					this.SendPropertyChanged("shareItId");
					this.OnshareItIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="BigInt NOT NULL")]
		public long userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._awUser_ShareIt.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awUser_ShareIt_awShareItWith", Storage="_awUser_ShareIt", ThisKey="userId", OtherKey="userId", IsForeignKey=true)]
		public awUser_ShareIt awUser_ShareIt
		{
			get
			{
				return this._awUser_ShareIt.Entity;
			}
			set
			{
				awUser_ShareIt previousValue = this._awUser_ShareIt.Entity;
				if (((previousValue != value) 
							|| (this._awUser_ShareIt.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._awUser_ShareIt.Entity = null;
						previousValue.awShareItWiths.Remove(this);
					}
					this._awUser_ShareIt.Entity = value;
					if ((value != null))
					{
						value.awShareItWiths.Add(this);
						this._userId = value.userId;
					}
					else
					{
						this._userId = default(long);
					}
					this.SendPropertyChanged("awUser_ShareIt");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awShareIt_awShareItWith", Storage="_awShareIt", ThisKey="shareItId", OtherKey="shareItId", IsForeignKey=true)]
		public awShareIt awShareIt
		{
			get
			{
				return this._awShareIt.Entity;
			}
			set
			{
				awShareIt previousValue = this._awShareIt.Entity;
				if (((previousValue != value) 
							|| (this._awShareIt.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._awShareIt.Entity = null;
						previousValue.awShareItWiths.Remove(this);
					}
					this._awShareIt.Entity = value;
					if ((value != null))
					{
						value.awShareItWiths.Add(this);
						this._shareItId = value.shareItId;
					}
					else
					{
						this._shareItId = default(long);
					}
					this.SendPropertyChanged("awShareIt");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awUser")]
	public partial class awUser_ShareIt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _userId;
		
		private string _username;
		
		private string _email;
		
		private string _password;
		
		private string _firstName;
		
		private string _lastName;
		
		private bool _isSuperAdmin;
		
		private bool _isEnabled;
		
		private bool _isDeleted;
		
		private string _imageurl;
		
		private string _link;
		
		private string _description;
		
		private string _gender;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _tel;
		
		private string _tel2;
		
		private string _fax;
		
		private string _address;
		
		private string _city;
		
		private string _state;
		
		private string _postalcode;
		
		private string _country;
		
		private System.Nullable<System.DateTime> _lastBuildDate;
		
		private System.DateTime _createDate;
		
		private EntitySet<awShareItWith> _awShareItWiths;
		
		private EntitySet<awSite_ShareIt> _awSite_ShareIts;
		
		private EntitySet<awShareIt> _awShareIts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIdChanging(long value);
    partial void OnuserIdChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnisSuperAdminChanging(bool value);
    partial void OnisSuperAdminChanged();
    partial void OnisEnabledChanging(bool value);
    partial void OnisEnabledChanged();
    partial void OnisDeletedChanging(bool value);
    partial void OnisDeletedChanged();
    partial void OnimageurlChanging(string value);
    partial void OnimageurlChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void Ontel2Changing(string value);
    partial void Ontel2Changed();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OnpostalcodeChanging(string value);
    partial void OnpostalcodeChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnlastBuildDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastBuildDateChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    #endregion
		
		public awUser_ShareIt()
		{
			this._awShareItWiths = new EntitySet<awShareItWith>(new Action<awShareItWith>(this.attach_awShareItWiths), new Action<awShareItWith>(this.detach_awShareItWiths));
			this._awSite_ShareIts = new EntitySet<awSite_ShareIt>(new Action<awSite_ShareIt>(this.attach_awSite_ShareIts), new Action<awSite_ShareIt>(this.detach_awSite_ShareIts));
			this._awShareIts = new EntitySet<awShareIt>(new Action<awShareIt>(this.attach_awShareIts), new Action<awShareIt>(this.detach_awShareIts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this.OnfirstNameChanging(value);
					this.SendPropertyChanging();
					this._firstName = value;
					this.SendPropertyChanged("firstName");
					this.OnfirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this.OnlastNameChanging(value);
					this.SendPropertyChanging();
					this._lastName = value;
					this.SendPropertyChanged("lastName");
					this.OnlastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSuperAdmin", DbType="Bit NOT NULL")]
		public bool isSuperAdmin
		{
			get
			{
				return this._isSuperAdmin;
			}
			set
			{
				if ((this._isSuperAdmin != value))
				{
					this.OnisSuperAdminChanging(value);
					this.SendPropertyChanging();
					this._isSuperAdmin = value;
					this.SendPropertyChanged("isSuperAdmin");
					this.OnisSuperAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isEnabled", DbType="Bit NOT NULL")]
		public bool isEnabled
		{
			get
			{
				return this._isEnabled;
			}
			set
			{
				if ((this._isEnabled != value))
				{
					this.OnisEnabledChanging(value);
					this.SendPropertyChanging();
					this._isEnabled = value;
					this.SendPropertyChanged("isEnabled");
					this.OnisEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDeleted", DbType="Bit NOT NULL")]
		public bool isDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if ((this._isDeleted != value))
				{
					this.OnisDeletedChanging(value);
					this.SendPropertyChanging();
					this._isDeleted = value;
					this.SendPropertyChanged("isDeleted");
					this.OnisDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageurl", DbType="NVarChar(255)")]
		public string imageurl
		{
			get
			{
				return this._imageurl;
			}
			set
			{
				if ((this._imageurl != value))
				{
					this.OnimageurlChanging(value);
					this.SendPropertyChanging();
					this._imageurl = value;
					this.SendPropertyChanged("imageurl");
					this.OnimageurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(255)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(512)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(2)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="VarChar(50)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel2", DbType="VarChar(50)")]
		public string tel2
		{
			get
			{
				return this._tel2;
			}
			set
			{
				if ((this._tel2 != value))
				{
					this.Ontel2Changing(value);
					this.SendPropertyChanging();
					this._tel2 = value;
					this.SendPropertyChanged("tel2");
					this.Ontel2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(50)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(255)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="NVarChar(50)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postalcode", DbType="NVarChar(20)")]
		public string postalcode
		{
			get
			{
				return this._postalcode;
			}
			set
			{
				if ((this._postalcode != value))
				{
					this.OnpostalcodeChanging(value);
					this.SendPropertyChanging();
					this._postalcode = value;
					this.SendPropertyChanged("postalcode");
					this.OnpostalcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(50)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastBuildDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastBuildDate
		{
			get
			{
				return this._lastBuildDate;
			}
			set
			{
				if ((this._lastBuildDate != value))
				{
					this.OnlastBuildDateChanging(value);
					this.SendPropertyChanging();
					this._lastBuildDate = value;
					this.SendPropertyChanged("lastBuildDate");
					this.OnlastBuildDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awUser_ShareIt_awShareItWith", Storage="_awShareItWiths", ThisKey="userId", OtherKey="userId")]
		public EntitySet<awShareItWith> awShareItWiths
		{
			get
			{
				return this._awShareItWiths;
			}
			set
			{
				this._awShareItWiths.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awUser_ShareIt_awSite_ShareIt", Storage="_awSite_ShareIts", ThisKey="userId", OtherKey="userId")]
		public EntitySet<awSite_ShareIt> awSite_ShareIts
		{
			get
			{
				return this._awSite_ShareIts;
			}
			set
			{
				this._awSite_ShareIts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awUser_ShareIt_awShareIt", Storage="_awShareIts", ThisKey="userId", OtherKey="userId")]
		public EntitySet<awShareIt> awShareIts
		{
			get
			{
				return this._awShareIts;
			}
			set
			{
				this._awShareIts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_awShareItWiths(awShareItWith entity)
		{
			this.SendPropertyChanging();
			entity.awUser_ShareIt = this;
		}
		
		private void detach_awShareItWiths(awShareItWith entity)
		{
			this.SendPropertyChanging();
			entity.awUser_ShareIt = null;
		}
		
		private void attach_awSite_ShareIts(awSite_ShareIt entity)
		{
			this.SendPropertyChanging();
			entity.awUser_ShareIt = this;
		}
		
		private void detach_awSite_ShareIts(awSite_ShareIt entity)
		{
			this.SendPropertyChanging();
			entity.awUser_ShareIt = null;
		}
		
		private void attach_awShareIts(awShareIt entity)
		{
			this.SendPropertyChanging();
			entity.awUser_ShareIt = this;
		}
		
		private void detach_awShareIts(awShareIt entity)
		{
			this.SendPropertyChanging();
			entity.awUser_ShareIt = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awSite")]
	public partial class awSite_ShareIt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _siteId;
		
		private string _alias;
		
		private string _title;
		
		private string _description;
		
		private bool _isEnabled;
		
		private string _cultureCode;
		
		private string _link;
		
		private string _imageurl;
		
		private System.Nullable<System.DateTime> _pubDate;
		
		private int _maxBlogs;
		
		private int _maxUsers;
		
		private int _maxContents;
		
		private System.Nullable<long> _userId;
		
		private System.Nullable<System.DateTime> _lastBuildDate;
		
		private System.Nullable<System.DateTime> _createDate;
		
		private EntitySet<awShareIt> _awShareIts;
		
		private EntityRef<awUser_ShareIt> _awUser_ShareIt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsiteIdChanging(long value);
    partial void OnsiteIdChanged();
    partial void OnaliasChanging(string value);
    partial void OnaliasChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnisEnabledChanging(bool value);
    partial void OnisEnabledChanged();
    partial void OncultureCodeChanging(string value);
    partial void OncultureCodeChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnimageurlChanging(string value);
    partial void OnimageurlChanged();
    partial void OnpubDateChanging(System.Nullable<System.DateTime> value);
    partial void OnpubDateChanged();
    partial void OnmaxBlogsChanging(int value);
    partial void OnmaxBlogsChanged();
    partial void OnmaxUsersChanging(int value);
    partial void OnmaxUsersChanged();
    partial void OnmaxContentsChanging(int value);
    partial void OnmaxContentsChanged();
    partial void OnuserIdChanging(System.Nullable<long> value);
    partial void OnuserIdChanged();
    partial void OnlastBuildDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastBuildDateChanged();
    partial void OncreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreateDateChanged();
    #endregion
		
		public awSite_ShareIt()
		{
			this._awShareIts = new EntitySet<awShareIt>(new Action<awShareIt>(this.attach_awShareIts), new Action<awShareIt>(this.detach_awShareIts));
			this._awUser_ShareIt = default(EntityRef<awUser_ShareIt>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alias", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				if ((this._alias != value))
				{
					this.OnaliasChanging(value);
					this.SendPropertyChanging();
					this._alias = value;
					this.SendPropertyChanged("alias");
					this.OnaliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(512)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isEnabled", DbType="Bit NOT NULL")]
		public bool isEnabled
		{
			get
			{
				return this._isEnabled;
			}
			set
			{
				if ((this._isEnabled != value))
				{
					this.OnisEnabledChanging(value);
					this.SendPropertyChanging();
					this._isEnabled = value;
					this.SendPropertyChanged("isEnabled");
					this.OnisEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cultureCode", DbType="NVarChar(2)")]
		public string cultureCode
		{
			get
			{
				return this._cultureCode;
			}
			set
			{
				if ((this._cultureCode != value))
				{
					this.OncultureCodeChanging(value);
					this.SendPropertyChanging();
					this._cultureCode = value;
					this.SendPropertyChanged("cultureCode");
					this.OncultureCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(255)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageurl", DbType="NVarChar(255)")]
		public string imageurl
		{
			get
			{
				return this._imageurl;
			}
			set
			{
				if ((this._imageurl != value))
				{
					this.OnimageurlChanging(value);
					this.SendPropertyChanging();
					this._imageurl = value;
					this.SendPropertyChanged("imageurl");
					this.OnimageurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pubDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> pubDate
		{
			get
			{
				return this._pubDate;
			}
			set
			{
				if ((this._pubDate != value))
				{
					this.OnpubDateChanging(value);
					this.SendPropertyChanging();
					this._pubDate = value;
					this.SendPropertyChanged("pubDate");
					this.OnpubDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxBlogs", DbType="Int NOT NULL")]
		public int maxBlogs
		{
			get
			{
				return this._maxBlogs;
			}
			set
			{
				if ((this._maxBlogs != value))
				{
					this.OnmaxBlogsChanging(value);
					this.SendPropertyChanging();
					this._maxBlogs = value;
					this.SendPropertyChanged("maxBlogs");
					this.OnmaxBlogsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxUsers", DbType="Int NOT NULL")]
		public int maxUsers
		{
			get
			{
				return this._maxUsers;
			}
			set
			{
				if ((this._maxUsers != value))
				{
					this.OnmaxUsersChanging(value);
					this.SendPropertyChanging();
					this._maxUsers = value;
					this.SendPropertyChanged("maxUsers");
					this.OnmaxUsersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxContents", DbType="Int NOT NULL")]
		public int maxContents
		{
			get
			{
				return this._maxContents;
			}
			set
			{
				if ((this._maxContents != value))
				{
					this.OnmaxContentsChanging(value);
					this.SendPropertyChanging();
					this._maxContents = value;
					this.SendPropertyChanged("maxContents");
					this.OnmaxContentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="BigInt")]
		public System.Nullable<long> userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._awUser_ShareIt.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastBuildDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastBuildDate
		{
			get
			{
				return this._lastBuildDate;
			}
			set
			{
				if ((this._lastBuildDate != value))
				{
					this.OnlastBuildDateChanging(value);
					this.SendPropertyChanging();
					this._lastBuildDate = value;
					this.SendPropertyChanged("lastBuildDate");
					this.OnlastBuildDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awSite_ShareIt_awShareIt", Storage="_awShareIts", ThisKey="siteId", OtherKey="siteId")]
		public EntitySet<awShareIt> awShareIts
		{
			get
			{
				return this._awShareIts;
			}
			set
			{
				this._awShareIts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awUser_ShareIt_awSite_ShareIt", Storage="_awUser_ShareIt", ThisKey="userId", OtherKey="userId", IsForeignKey=true)]
		public awUser_ShareIt awUser_ShareIt
		{
			get
			{
				return this._awUser_ShareIt.Entity;
			}
			set
			{
				awUser_ShareIt previousValue = this._awUser_ShareIt.Entity;
				if (((previousValue != value) 
							|| (this._awUser_ShareIt.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._awUser_ShareIt.Entity = null;
						previousValue.awSite_ShareIts.Remove(this);
					}
					this._awUser_ShareIt.Entity = value;
					if ((value != null))
					{
						value.awSite_ShareIts.Add(this);
						this._userId = value.userId;
					}
					else
					{
						this._userId = default(Nullable<long>);
					}
					this.SendPropertyChanged("awUser_ShareIt");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_awShareIts(awShareIt entity)
		{
			this.SendPropertyChanging();
			entity.awSite_ShareIt = this;
		}
		
		private void detach_awShareIts(awShareIt entity)
		{
			this.SendPropertyChanging();
			entity.awSite_ShareIt = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.awShareIt")]
	public partial class awShareIt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _shareItId;
		
		private long _siteId;
		
		private string _title;
		
		private string _description;
		
		private string _link;
		
		private bool _shareWithEveryone;
		
		private long _userId;
		
		private System.DateTime _createDate;
		
		private EntitySet<awShareItWith> _awShareItWiths;
		
		private EntityRef<awSite_ShareIt> _awSite_ShareIt;
		
		private EntityRef<awUser_ShareIt> _awUser_ShareIt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnshareItIdChanging(long value);
    partial void OnshareItIdChanged();
    partial void OnsiteIdChanging(long value);
    partial void OnsiteIdChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnshareWithEveryoneChanging(bool value);
    partial void OnshareWithEveryoneChanged();
    partial void OnuserIdChanging(long value);
    partial void OnuserIdChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    #endregion
		
		public awShareIt()
		{
			this._awShareItWiths = new EntitySet<awShareItWith>(new Action<awShareItWith>(this.attach_awShareItWiths), new Action<awShareItWith>(this.detach_awShareItWiths));
			this._awSite_ShareIt = default(EntityRef<awSite_ShareIt>);
			this._awUser_ShareIt = default(EntityRef<awUser_ShareIt>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shareItId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long shareItId
		{
			get
			{
				return this._shareItId;
			}
			set
			{
				if ((this._shareItId != value))
				{
					this.OnshareItIdChanging(value);
					this.SendPropertyChanging();
					this._shareItId = value;
					this.SendPropertyChanged("shareItId");
					this.OnshareItIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="BigInt NOT NULL")]
		public long siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					if (this._awSite_ShareIt.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(512)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(512)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shareWithEveryone", DbType="Bit NOT NULL")]
		public bool shareWithEveryone
		{
			get
			{
				return this._shareWithEveryone;
			}
			set
			{
				if ((this._shareWithEveryone != value))
				{
					this.OnshareWithEveryoneChanging(value);
					this.SendPropertyChanging();
					this._shareWithEveryone = value;
					this.SendPropertyChanged("shareWithEveryone");
					this.OnshareWithEveryoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="BigInt NOT NULL")]
		public long userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._awUser_ShareIt.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awShareIt_awShareItWith", Storage="_awShareItWiths", ThisKey="shareItId", OtherKey="shareItId")]
		public EntitySet<awShareItWith> awShareItWiths
		{
			get
			{
				return this._awShareItWiths;
			}
			set
			{
				this._awShareItWiths.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awSite_ShareIt_awShareIt", Storage="_awSite_ShareIt", ThisKey="siteId", OtherKey="siteId", IsForeignKey=true)]
		public awSite_ShareIt awSite_ShareIt
		{
			get
			{
				return this._awSite_ShareIt.Entity;
			}
			set
			{
				awSite_ShareIt previousValue = this._awSite_ShareIt.Entity;
				if (((previousValue != value) 
							|| (this._awSite_ShareIt.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._awSite_ShareIt.Entity = null;
						previousValue.awShareIts.Remove(this);
					}
					this._awSite_ShareIt.Entity = value;
					if ((value != null))
					{
						value.awShareIts.Add(this);
						this._siteId = value.siteId;
					}
					else
					{
						this._siteId = default(long);
					}
					this.SendPropertyChanged("awSite_ShareIt");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="awUser_ShareIt_awShareIt", Storage="_awUser_ShareIt", ThisKey="userId", OtherKey="userId", IsForeignKey=true)]
		public awUser_ShareIt awUser_ShareIt
		{
			get
			{
				return this._awUser_ShareIt.Entity;
			}
			set
			{
				awUser_ShareIt previousValue = this._awUser_ShareIt.Entity;
				if (((previousValue != value) 
							|| (this._awUser_ShareIt.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._awUser_ShareIt.Entity = null;
						previousValue.awShareIts.Remove(this);
					}
					this._awUser_ShareIt.Entity = value;
					if ((value != null))
					{
						value.awShareIts.Add(this);
						this._userId = value.userId;
					}
					else
					{
						this._userId = default(long);
					}
					this.SendPropertyChanged("awUser_ShareIt");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_awShareItWiths(awShareItWith entity)
		{
			this.SendPropertyChanging();
			entity.awShareIt = this;
		}
		
		private void detach_awShareItWiths(awShareItWith entity)
		{
			this.SendPropertyChanging();
			entity.awShareIt = null;
		}
	}
}
#pragma warning restore 1591
